# dit bestand laat ons toe de app te configureren.
#definieer welke runtime we willen gebruiken:
runtime: python37

#definieer type van scaling (F=autoscaling)
instance_class: F2

#Hoe URL patronen verwerkt moeten worden
handlers:
- url: /.*
  secure: always
  script: auto

service: svc_milanvelle